Cadastrar familia
LilianeBifano/financasemfamilia pull request #6
Opened 2018-07-26 00:44 UTC by mvbvieira

2018-07-26 01:08 UTC, joaorsalmeida requested changes

2018-07-26 01:08 UTC, joaorsalmeida commented on app/controllers/application_controller.rb
> +  def return_conditions
Esse nome nao deixa claro o que esta sendo avaliado.

2018-07-26 01:08 UTC, joaorsalmeida commented on app/controllers/application_controller.rb
> +  def require_login
Require login? Não seria melhor algo como `check_family_registered` por ex?

2018-07-26 01:08 UTC, joaorsalmeida commented on app/views/families/new.html.erb
> +<h1><%= I18n.t(:new_family) %></h1>
Essa view poderia ter um titulo pelo menos

2018-07-26 01:08 UTC, joaorsalmeida commented on app/views/families/show.html.erb
> +<p>Familia: <%= @family.name%></p>
Só nome da familia esta ok nessa view?

2018-07-26 01:08 UTC, joaorsalmeida commented on app/views/profiles/show.html.erb
> +<p> <%=link_to 'Cadastrar Familia', new_family_path %> </p>
O usuário pode cadastrar mais de uma familia?

2018-07-26 15:12 UTC, HenriqueMorato commented on app/controllers/families_controller.rb
> +    @family = Family.find(params[:id])
Seria legal ter um teste pra verificar se o usuário tá vendo a familia dele mesmo ou se pode ver de outra pessoa.

2018-07-26 17:06 UTC, eduardoekoch commented on app/controllers/application_controller.rb
> +  def return_conditions
João, tem alguma sugestão?

2018-07-26 17:08 UTC, eduardoekoch commented on app/controllers/application_controller.rb
> +  def require_login
Alterado.

2018-07-26 17:12 UTC, eduardoekoch commented on app/views/families/new.html.erb
> +<h1><%= I18n.t(:new_family) %></h1>
alterado

2018-07-26 17:12 UTC, eduardoekoch commented on app/views/families/show.html.erb
> +<p>Familia: <%= @family.name%></p>
Aterado

2018-07-26 17:13 UTC, eduardoekoch commented on app/views/profiles/show.html.erb
> +<p> <%=link_to 'Cadastrar Familia', new_family_path %> </p>
Não deveria. Iremos corrigir

2018-07-27 00:17 UTC, joaorsalmeida approved these changes

2018-07-27 00:17 UTC, merged